### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by puzzlepeaches** [Tw1sm/spraycharles#3]
### Ask

Hey there, awesome project! Really looking to integrate this into my workflow and was hoping you might be able to help implement a couple of features. Problems:

1. I often come up with some other password ideas during spraying and would like to add them to the existing password list. The same goes for usernames.
2. Also I would like to integrate third-party notification functionality into the tool, but the analyzer isn't run after every spraying attempt. This makes it so I can only add a notification operation wherein I am notified after the long-running spray is complete. 

### Solution

It would be awesome if we could implement the following to solve both problems:

1. Use something similar to the [TargetsFileWatcher](https://github.com/SecureAuthCorp/impacket/blob/14578b53079645a94f965199c7d0c4796a31b2f0/impacket/examples/ntlmrelayx/utils/targetsutils.py#L154) class here from impacket for user and password lists so the next spray iterations include any updates to user/pass files. 
2. Issue the `analyze.Analyzer(csvfile)` operation on line 200 in spraycharles every time a spray is complete as opposed to once all passwords are attempted. This could be something that is only done if a flag is added to our original command etc

### 

In the near future, I hope to add an NTLM password spraying module and some notification functionality to spraycharles. I look forward to your response! Nice work!

**Comment by Tw1sm** [comment]
Hey, thanks for the feedback! Posted my initial thoughts below and I'll update this thread again as progress is made.

### Watching for updates in user/pass files
I'll check out the Impacket class you linked to and see what I can do there. Another one of my team members has mentioned this idea in the past, so it's definitely worth implementing.

### Analyzing results after each loop
This is something I've thought about before but was hesitant to implement because, without enough response code data in the output file, the analyzer will be prone to false positives. Maybe there is an in-between solution or threshold that can be set so false positives aren't a problem while still offering results more frequently during the spray.

### NTLM Spraying
This would be a great addition. I recently was playing with an SMB module for spraying during internal testing - I've got an SMB branch that hasn't been merged into master yet. I bet this could be tweaked to offer an NTLM option.

**Comment by Tw1sm** [comment]
@puzzlepeaches commit e782fda00cb2c9a7bf2f5c5f9e495500638a86dd should address problem 1 and commit fe710cdcfd82c88ef823260df1c9f4f086e4f41a should address problem 2. Please give them a test and let me know if it's functioning how you envisioned.

User/pass files just simply get read again at the start of each spray interval and any new additions get thrown in the user/pass lists. Only works for additions, removing something from a file will have any effect.

New `--analyze` flag will optionally allow you to analyze results after each spray interval. I'm still not sure how accurate this will be early on, especially for small user pools - it will probably depend on the target. When response length varies by username length, it tends to get a little messy since wildly long/short usernames will appear as hits until enough data gets collected.

Here's an example of a spray with the `smb` module where the `--analyze` flag was used and I edited the username file after start:
<img src="https://user-images.githubusercontent.com/37981031/111492659-3d72e380-8713-11eb-9719-a2cfda44667e.png" height="550">

**Comment by puzzlepeaches** [comment]
Ahhh, nice man! I will give these additions a test as soon as I get time! Thanks for the super quick turnaround.

**Comment by puzzlepeaches** [comment]
So little update, just landed on an account for an engagement using the --analyze flag during spraying so that is for sure working well! Seriously it is such a good idea to look at the size of responses instead of checking for some hard-coded identifier.

I am going to start working on a variation of a module today with notification integrations. I am going to close this out and hopefully I'll be able to make a pull request soon. Feel free to hit me up here or on Twitter @sprocket_ed if I can help out with anything. Thanks man!

**Comment by Tw1sm** [comment]
Awesome, that's great to hear. I'll close this issue out for now. Looking forward to seeing what you come up with.
